### ISSUE TITLE
deserialize_meta won't union properly

### ISSUE THREAD

**Issue by admire93** [spoqa/nirum-python#34]
https://gitter.im/spoqa/nirum?at=57dd736133c63ba01a0e09e2

**Comment by dahlia** [comment]
@admire93 Although PR #35 fixed it to work, we need to refactor the generated code to be conciser and more efficient than now.

- The compiler should generate `__nirum_type__ = 'union'  # or 'record'/'tag'/'enum'/'boxed'` so that the runtime can determine what Nirum type the given Python class is generated from.
- Also, the compiler should generate `__nirum_tag_classes__ = {Tag.tag_name: TagName, ...}` so that the runtime can lookup the corresponding Python class by the given tag name in O(1).  The current implementation loops over `cls.__subclasses__()` which is O(n).
